/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/crystal.glb -o src/components/Crystal.tsx -r public --types 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useExplode } from "@/hooks/useExplode";
import { useOrbit } from "@/hooks/useOrbit";

type GLTFResult = GLTF & {
  nodes: {
    Icosphere: THREE.Mesh;
    Icosphere_cell: THREE.Mesh;
    Icosphere_cell001: THREE.Mesh;
    Icosphere_cell002: THREE.Mesh;
    Icosphere_cell003: THREE.Mesh;
    Icosphere_cell004: THREE.Mesh;
    Icosphere_cell005: THREE.Mesh;
    Icosphere_cell006: THREE.Mesh;
    Icosphere_cell007: THREE.Mesh;
    Icosphere_cell008: THREE.Mesh;
    Icosphere_cell009: THREE.Mesh;
    Icosphere_cell010: THREE.Mesh;
    Icosphere_cell011: THREE.Mesh;
    Icosphere_cell012: THREE.Mesh;
    Icosphere_cell013: THREE.Mesh;
    Icosphere_cell014: THREE.Mesh;
    Icosphere_cell015: THREE.Mesh;
    Icosphere_cell016: THREE.Mesh;
    Icosphere_cell017: THREE.Mesh;
    Icosphere_cell018: THREE.Mesh;
    Icosphere_cell019: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const Crystal = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/crystal.glb") as GLTFResult;

  const group = useRef<THREE.Group>(null);

  useExplode(group, { distance: 3 });

  useOrbit(group, { radius: 1, speed: 1 ,origin: new THREE.Vector3(0, 0, 0)});

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.Icosphere.geometry}
        material={materials["Material.002"]}
        scale={[1, 2.218, 1]}
      />
      <mesh
        geometry={nodes.Icosphere_cell.geometry}
        material={materials["Material.002"]}
        position={[0.447, -0.365, 0.316]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell001.geometry}
        material={materials["Material.002"]}
        position={[-0.147, -0.049, 0.328]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell002.geometry}
        material={materials["Material.002"]}
        position={[-0.433, -0.373, -0.18]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell003.geometry}
        material={materials["Material.002"]}
        position={[-0.115, -0.392, -0.497]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell004.geometry}
        material={materials["Material.002"]}
        position={[0.547, -0.474, -0.268]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell005.geometry}
        material={materials["Material.002"]}
        position={[0.115, 0.956, 0.401]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell006.geometry}
        material={materials["Material.002"]}
        position={[-0.357, 1.012, 0.088]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell007.geometry}
        material={materials["Material.002"]}
        position={[-0.268, 0.681, -0.439]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell008.geometry}
        material={materials["Material.002"]}
        position={[0.26, 0.806, -0.388]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell009.geometry}
        material={materials["Material.002"]}
        position={[0.513, 0.788, 0.028]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell010.geometry}
        material={materials["Material.002"]}
        position={[0.381, -0.908, 0.078]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell011.geometry}
        material={materials["Material.002"]}
        position={[-0.107, -0.927, 0.412]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell012.geometry}
        material={materials["Material.002"]}
        position={[0.443, -0.92, -0.395]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell013.geometry}
        material={materials["Material.002"]}
        position={[-0.351, -0.913, 0.149]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell014.geometry}
        material={materials["Material.002"]}
        position={[-0.026, -0.928, -0.422]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell015.geometry}
        material={materials["Material.002"]}
        position={[0.203, 1.489, 0.106]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell016.geometry}
        material={materials["Material.002"]}
        position={[0.099, 1.598, 0.271]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell017.geometry}
        material={materials["Material.002"]}
        position={[-0.166, 1.51, 0.076]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell018.geometry}
        material={materials["Material.002"]}
        position={[-0.192, 1.39, -0.262]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Icosphere_cell019.geometry}
        material={materials["Material.002"]}
        position={[0.125, 1.448, -0.161]}
        scale={0.99}
      />
    </group>
  );
};

useGLTF.preload("/models/crystal.glb");
